services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    env_file:
      - .env

  db:
    image: postgres:16
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:6.2
    command: redis-server
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-store:
  bundle_data:
