# fly.toml app configuration file generated for english-diary on 2024-09-28T13:27:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'english-diary'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
