:concurrency: 5
:queues:
  - default
  - mailers

:strict: false

:redis:
  :url: <%= ENV.fetch('REDIS_URL') %> # 環境変数からREDIS_URLを取得

:scheduler:
  :schedule:
    send_reminders_job:
      cron: "*/1 * * * *"
      class: "SendRemindersJob"
      queue: default
